### ISSUE TITLE
flutter/dart client?

### ISSUE THREAD

**Issue by ayushin** [chatwoot/chatwoot-flutter-sdk#1]
Are there any plans / work done on building a flutter chat client?

**Comment by sojan-official** [comment]
@EphraimNetWorks  The 401 in documentation seems like a mistake. it should be 404, we will have it updated. 
A quick note on the readme, it looks great. Just a minor thing I spotted in 

> 1. Create an API inbox in Chatwoot
it links to the website channel. we should link to https://www.chatwoot.com/docs/product/channels/api/create-channel


@ayushin @EricHier if you could test the SDK and give some feedback to @EphraimNetWorks  That would super helpful.

**Comment by EphraimNetWorks** [comment]
@sojan-official Thanks for the feedback. I'll push the corrections and updates and let you know if I run into any issues

**Comment by EphraimNetWorks** [comment]
@sojan-official Could you add me as a collaborator here, I want to update the develop branch with the recent changes from the test repo and update the documentation with the corrections you suggested. 
Also want to ask if you could provide sample json payload for each of the exposed websocket events? Thanks

**Comment by sojan-official** [comment]
@EphraimNetWorks  I have added you as a collaborator. will get you the documentation for socket events by end of this week.

**Comment by EphraimNetWorks** [comment]
@sojan-official Yeah I saw, I've accepted it thanks. I have updated the documentation with the correction. Also changed the github repo url to this repo. Added some bug fixes for the ChatwootChatDialog too. I'll be testing more and fix any issues found

**Comment by sojan-official** [comment]
@EphraimNetWorks  I have raised a PR with the documentation https://github.com/chatwoot/docs/pull/65 . we will get it merged by Monday. This contains payload samples for all the available websocket events.

**Comment by EphraimNetWorks** [comment]
@sojan-official Would it be published to the same url as the [Client Api Docs](https://www.chatwoot.com/docs/product/channels/api/client-apis)?

**Comment by ayushin** [comment]
Wonderful start guys!

Just before you go further, I'd seriously consider breaking this down into two packages from the very start:
1) purely dart `packages/chatwoot-sdk`
2) ui library `packages/chatwoot-flutter`

These two can (should) live in the same repository though

**Comment by EphraimNetWorks** [comment]
That was the plan initially, but I ended up going with the "merged version" looking at the extra work it'll take to maintain two packages for a single client sdk. Tried as much as possible to decouple the chats ui layer from the any chatwoot operation, so in case the need arises in the future for separate packages it should be fairly easy to separate them. 

1. So for purely dart purposes, you could use a ChatwootClient instance and handle events through callbacks.
2. If you something quick, you simply use the widget and customize the theme

For now I think a single package would be best, 
1. Single source of truth
2. Easier to maintain
3. Main flutter platforms (Android, iOS and Web) are supported

**Comment by ayushin** [comment]
I think there is no point reinventing the wheel and creating yet another chat widget, dash_chat does a great job already and there are many more on pub.dev

**Comment by sojan-official** [comment]
> @sojan-official Would it be published to the same url as the [Client Api Docs](https://www.chatwoot.com/docs/product/channels/api/client-apis)?

https://www.chatwoot.com/docs/product/others/websocket-events

**Comment by EphraimNetWorks** [comment]
> I think there is no point reinventing the wheel and creating yet another chat widget, dash_chat does a great job already and there are many more on pub.dev

The ChatwootChatWidget actually uses the chat ui from the [Flutter Chat UI](https://pub.dev/packages/flutter_chat_ui) package whose UI is similar to the website's chatwoot widget

**Comment by EphraimNetWorks** [comment]
> > @sojan-official Would it be published to the same url as the [Client Api Docs](https://www.chatwoot.com/docs/product/channels/api/client-apis)?
> 
> https://www.chatwoot.com/docs/product/others/websocket-events

@sojan-official Went through the docs, saw three events are missing from the current flutter package (would be adding them). `message_updated` and `conversation_read` seems straightforward to understand. Want to ask what happens on client side should a `conversation_status_changed` event be received?

**Comment by ayushin** [comment]
> > I think there is no point reinventing the wheel and creating yet another chat widget, dash_chat does a great job already and there are many more on pub.dev
> 
> The ChatwootChatWidget actually uses the chat ui from the [Flutter Chat UI](https://pub.dev/packages/flutter_chat_ui) package whose UI is similar to the website's chatwoot widget

I think this is starting a loosing battle here. Have you considered this approach?

https://github.com/chatwoot/chatwoot-flutter-sdk/issues/9

**Comment by EphraimNetWorks** [comment]
Seems like a good approach but I'm not sure the widget was designed to be used in that way

**Comment by ayushin** [comment]
Well it actually works for us and worked before with TileDesk (and works for a number of major apps using TileDesk)

**Comment by sojan-official** [comment]
> > > @sojan-official Would it be published to the same url as the [Client Api Docs](https://www.chatwoot.com/docs/product/channels/api/client-apis)?
> > 
> > 
> > https://www.chatwoot.com/docs/product/others/websocket-events
> 
> @sojan-official Went through the docs, saw three events are missing from the current flutter package (would be adding them). `message_updated` and `conversation_read` seem straightforward to understand. Want to ask what happens on client-side should a `conversation_status_changed` event be received?

The idea behind `conversation_status_changed` is that we could use it to prevent contact from sending messages after the agent resolves the conversation. This is geared towards the future where we want to support multiple conversations in the widget. 

At the moment in the Chatwoot web widget, we disable the input based on the combination of whether csat surveys are enabled for a chat + receiving the `conversation_status_changed` event with resolved status.

**Comment by EphraimNetWorks** [comment]
Apart from the `conversation_status_changed` event is there another way to check for the status of a conversation? Looking at a case where user isn't connected to the websocket channel when conversation was resolved. To support multiple conversations I'm looking at clearing cached conversation id and messages when conversation is resolved, then creating a new conversation for that contact.

**Comment by EphraimNetWorks** [comment]
@sojan-official For the UI, when a conversation resolved event is received.  a bot message can be shown to user on ticket being marked as resolved (could also contain a link to csat survey). Any thoughts on this?
Also want to ask how to determine if csat survey is enabled for a conversation.

**Comment by sojan-official** [comment]
> Apart from the `conversation_status_changed` event is there another way to check for the status of a conversation? Looking at a case where user isn't connected to the websocket channel when conversation was resolved. To support multiple conversations I'm looking at clearing cached conversation id and messages when the conversation is resolved, then creating a new conversation for that contact.

https://www.chatwoot.com/developers/api#operation/list-all-contact-conversations

**Comment by sojan-official** [comment]
> @sojan-official For the UI, when a conversation resolved event is received. a bot message can be shown to user on ticket being marked as resolved (could also contain a link to csat survey). Any thoughts on this?
> Also want to ask how to determine if csat survey is enabled for a conversation.

That sounds good to me. we could replicate the same behavior as the chat widget and show a new conversation button. 
Once this PR: https://github.com/chatwoot/chatwoot/pull/2749 gets merged, the system will determine whether csat is enabled in that inbox and will send a link.

**Comment by bulanni00** [comment]
Flutter When can it be used

**Comment by EphraimNetWorks** [comment]
It can be used as it is. One feature left is sending message with attachment. Currently sending message with attachment using the public client API returns a 500 internal server error. I just raised the bug in the discord channel. Should be able to wrap up the sdk once that's fixed.

**Comment by sojan-official** [comment]
@EphraimNetWorks  We will take a look and get back.

**Comment by engmsaleh** [comment]
Nice work guys, I have added the SDK to my app but got the following issue

It is working, but I got an issue and multiple points that I want to understand

- As I understand, I have created an API inbox without a Callback URL, then got the `inbox_identifier` 
Widget Open-up, but I got a crash on as `pubsub_token` is null
- When I send a message, what only appears on the dashboard, Is that I have a conversation assigned to me with No Messages
- Same happens from Chatwoot mobile apps
Any help or advice?

**Comment by ayushin** [comment]
I still fail to understand why not use a mature SDK like flyer.chat  and just build chatwoot backend for it.

**Comment by engmsaleh** [comment]
@ayushin This sounds like a nice setup, Did you make such a setup, or can guide me so to try it?

**Comment by engmsaleh** [comment]
As I understand this SDK is already using `flyer.chat` according to documentation `NB: This library uses [Hive](https://pub.dev/packages/hive) for local storage and [Flutter Chat UI](https://pub.dev/packages/flutter_chat_ui) for its user interface`
Or do I misssomething?

**Comment by sojan-official** [comment]
Closing this since we have updated repo and verified it to be working
