### ISSUE TITLE
pubsub_token is null 

### ISSUE THREAD

**Issue by imhafeez** [chatwoot/chatwoot-flutter-sdk#13]
on calling `ChatwootChatDialog.show` it creates a new contact it returns the contact with pubsub_token as null and throughs exception

`Unhandled Exception: type 'Null' is not a subtype of type 'String' in type cast`

<img width="1067" alt="Screenshot 2021-12-31 at 10 36 22 PM" src="https://user-images.githubusercontent.com/21155655/147834302-6bb1533e-0dfa-4e0d-901e-7f813ffb5fd0.png">

**Comment by engmsaleh** [comment]
@imhafeez Same happens to me, Do you have solved that?

**Comment by imhafeez** [comment]
@engmsaleh use the forked one. I have fixed that:

```
chatwoot_client_sdk:
    git: 'https://github.com/imhafeez/chatwoot-flutter-sdk.git'
```

**Comment by engmsaleh** [comment]
@imhafeez Worked like a charm, thanks a lot

> @engmsaleh use the forked one. I have fixed that:
> 
> ```
> chatwoot_client_sdk:
>     git: 'https://github.com/imhafeez/chatwoot-flutter-sdk.git'
> ```

**Comment by sojan-official** [comment]
@imhafeez Can we merge the changes on your fork to upstream?

**Comment by imhafeez** [comment]
sure @sojan-official . go for it.

**Comment by uday0117** [comment]
json[pubsub_token]!=null? "":json [pubsub_token] as String;

this will work fine for me
