### ISSUE TITLE
Messages not sending with ChatwootChat widget?

### ISSUE THREAD

**Issue by joelr45** [chatwoot/chatwoot-flutter-sdk#34]
Hey guys, so I have followed your instructions from: https://github.com/chatwoot/chatwoot-flutter-sdk#b-using-chatwootchat-widget

I can set the user, but the messages are not sending through. Am I missing something here?

**Comment by Babs95** [comment]
Hi joelr45, I'm also facing the same issue

**Comment by angebagui** [comment]
Hello I have the same problem

**Comment by slfhstr** [comment]
Yeah, me too 👎 
No response from chatwoot in almost 2 weeks ?

**Comment by sojan-official** [comment]
@iamsivin  could you take a look ?

**Comment by joelr45** [comment]
Hey guys, just wanted to check in again. Any update?

**Comment by angebagui** [comment]
Still nothing.

**Comment by iamsivin** [comment]
@joelr45 Do you follow all the steps from here? 
https://github.com/chatwoot/chatwoot-flutter-sdk#a-using-chatwootchatdialog
We tested it from our end, and it's working fine. You can see this in the loom video attached below.
https://www.loom.com/share/ed1493914d4b47eab60848dae178235e

Can you guys share more details?

**Comment by angebagui** [comment]
I have used this https://github.com/chatwoot/chatwoot-flutter-sdk#a-using-chatwootchatdialog
but i have the same bug
https://www.loom.com/share/774aac597004416dabf871ed37b5453c

**Comment by joelr45** [comment]
@iamsivin Thanks for the reply, yeah, I have followed through with the documentation, but I am seeing the exact same behavior as @angebagui. Hmmm...

**Comment by angebagui** [comment]
Hey guys, just wanted to check in again. Any update?

**Comment by iamsivin** [comment]
@joelr45 @angebagui The package on the pub is not updated. You can build from the repo until that's resolved.

**Comment by iamsivin** [comment]
@joelr45 @angebagui @Babs95 @timconsidine  Can you guys try using https://pub.dev/packages/chatwoot_sdk? This version will solve the issue that messages are not sending.
You can try this `flutter pub add chatwoot_sdk` instead of this `flutter pub add chatwoot_client_sdk` for adding Chatwoot SDK.

**Comment by angebagui** [comment]
Great, Thank you very much.

**Comment by iamsivin** [comment]
[Closing this issue as it is resolved.](https://github.com/chatwoot/chatwoot-flutter-sdk/issues/34#issuecomment-1401764542)
