### ISSUE TITLE
openapi

### ISSUE THREAD

**Issue by ayushin** [chatwoot/chatwoot-flutter-sdk#6]
Another great approach would be to use openapi standard (preferably generated) to describe the api endpoints that later on can be used to generate a dart client (or js or python or java) with openapi-generator

Thats saves a lot of time developing clients - all the api endpoints and models are generated for you.

Instead of rebuilding the api for each client, you could auto-generate it, it would speed up a lot building something like

https://github.com/chatwoot/chatwoot-flutter-sdk/issues/1

**Comment by ayushin** [comment]
This kind of beautiful documentation (along with models and code) can be just auto-generated:

https://api.mattermost.com/

**Comment by sojan-official** [comment]
we have API specification already available at https://www.chatwoot.com/developers/api

**Comment by ayushin** [comment]
That's a great start unfortunately only good for documentation and not good enough for automatic code generation - no models are defined and a lot of inconsistencies. (try `openapi-generator generate -g javascript -i swagger.json`)

**Comment by nosovk** [comment]
https://www.chatwoot.com/developers/swagger.json
it seems that schema improved now.
