### ISSUE TITLE
chatwoot webview

### ISSUE THREAD

**Issue by ayushin** [chatwoot/chatwoot-flutter-sdk#9]
While building chatwoot-flutter-sdk is a longer project, I think you could achieve great immediate results by creating a simple webview package that would simply load the chatwoot widget into a full screen webview inside of a flutter app.

That's the approach widely done by other chats. At a very basic level it would be just doing `launch('https://app.chatwoot.com/widget?website_token=....` however it would be great to actually build up the similar html inside of the flutter app so that you are able to set the user identity, i.e you'd call a widget:

```
ChatwootWebView(
    url='https://app.chatwoot.com/widget',
    websiteToken='..... ',
    userName: ...
    userEmail: ..
    userAvatarUrl: ....
    identifierHash: ...
```

This is much less work and would make chatwoot immediately available to the flutter community with the same production quality of the widget as you have now (i.e. avoid lengthy testing/improvement cycle you'd have building a whole new sdk / ui widgets)

@EphraimNetWorks is this something you could consider looking at?

**Comment by EphraimNetWorks** [comment]
Seems like a good approach but I'm not sure the widget was designed to be used in this way. Try launching the url `https://app.chatwoot.com/widget?website_token=....` in a your browser, start a conversation then refresh the page. You realize all messages are cleared and a new contact & conversation will need to be created.

>however it would be great to actually build up the similar html inside of the flutter app so that you are able to set the user identity, i.e you'd call a widget

So that's what has been done for the current package, just in this case instead of using html, dart is used

**Comment by ayushin** [comment]
@EphraimNetWorks why did you close the issue? it was not you who opened it.

@pranavrajs we would like to try this implementation, but we need some help understanding how to pass 
 identity hash to `https://app.chatwoot.com/widget?` or alternatively how we can use javascript widget in full screen mode.

**Comment by EphraimNetWorks** [comment]
@ayushin Sorry about that, would you like to create a PR for this approach?

**Comment by ayushin** [comment]
@EphraimNetWorks Thanks for re-opening,  yes we will try.

**Comment by ayushin** [comment]
OK, so the alternative approach is:

https://github.com/apexlabs-ai/chatwoot-flutter-webview

https://pub.dev/packages/chatwoot_flutter_webview

**Comment by EphraimNetWorks** [comment]
A webview option has been implemented in this SDK. Closing this issue

**Comment by EphraimNetWorks** [comment]
A webview option has been implemented in this SDK. Closing this issue
